#ifndef PMD_Diagnostics
#define PMD_Diagnostics

//  PMDDiagnostics.h -- diagnostic functions
//
//  Performance Motion Devices, Inc.
//

#if defined(__cplusplus)
extern "C" {
#endif
    
    
    struct tagPMDOpcodeText {
        PMDuint16 opcode;
        const char*     text;
        const char*     pad;
    } PMDOpcodeText[] = {
        {PMDOPNoOperation,              "Nop","                   "},
        {0x01,                          "Invalid opcode!","       "},
        {PMDOPSetMotorType,             "SetMotorType(Mag)","     "},
        {PMDOPGetMotorType,             "GetMotorType(Mag)","     "},
        {PMDOPSetBiQuadCoefficient,     "SetBiQuadCoef(Mag)","    "},
        {PMDOPGetBiQuadCoefficient,     "GetBiQuadCoef(Mag)","    "},
        {PMDOPSetMotorLimit,            "SetMotorLimit","         "},
        {PMDOPGetMotorLimit,            "GetMotorLimit","         "},
        {PMDOPSetAuxilliaryEncoderSource,"SetAuxEncSrc(Mag)","     "},
        {PMDOPGetAuxilliaryEncoderSource,"GetAuxEncSrc(Mag)","     "},
        {PMDOPSetSPIMode,               "SetSPIMode(Mag)","       "},
        {PMDOPGetSPIMode,               "GetSPIMode(Mag)","       "},
        {PMDOPSetPWMFrequency,          "SetPWMFreq(Mag)","       "},
        {PMDOPGetPWMFrequency,          "GetPWMFreq(Mag)","       "},
        {0x0E,                          "GetDriveStatus(ION)","   "},
        {PMDOPSetMotorBias,             "SetMotorBias","          "},
        
        {PMDOPSetPosition,              "SetPosition","           "},
        {PMDOPSetVelocity,              "SetVelocity","           "},
        {PMDOPSetCANMode,               "SetCANMode(Mag)","       "},
        {PMDOPSetJerk,                  "SetJerk","               "},
        {PMDOPSetGearRatio,             "SetGearRatio","          "},
        {PMDOPGetCANMode,               "GetCANMode(Mag)","       "},
        {0x16,                          "Invalid opcode!","       "},
        {0x17,                          "Invalid opcode!","       "},
        {0x18,                          "Invalid opcode!","       "},
        {0x19,                          "Invalid opcode!","       "},
        {PMDOPUpdate,                   "Update","                "},
        {0x1B,                          "Invalid opcode!","       "},
        {0x1C,                          "Invalid opcode!","       "},
        {PMDOPGetCommandedPosition,     "GetCommandedPosition","  "},
        {PMDOPGetCommandedVelocity,     "GetCommandedVelocity","  "},
        {0x1F,                          "Invalid opcode!","       "},

        {0x20,                          "Invalid opcode!","       "},
        {0x21,                          "Invalid opcode!","       "},
        {0x22,                          "Invalid opcode!","       "},
        {0x23,                          "Invalid opcode!","       "},
        {0x24,                          "Invalid opcode!","       "},
        {PMDOPSetKp,                    "SetKp","                 "},
        {PMDOPSetKi,                    "SetKi","                 "},
        {PMDOPSetKd,                    "SetKd","                 "},
        {0x28,                          "Invalid opcode!","       "},
        {0x29,                          "Invalid opcode!","       "},
        {0x2A,                          "Invalid opcode!","       "},
        {PMDOPSetKvff,                  "SetKvff","               "},
        {PMDOPGetPhaseAngle,            "GetPhaseAngle","         "},
        {PMDOPGetMotorBias,             "GetMotorBias","          "},
        {PMDOPRestoreOperatingMode,     "RestoreOperatingMode","  "},
        {PMDOPSetInterruptMask,         "SetInterruptMask","      "},
        
        {0x30,                          "Invalid opcode!","       "},
        {PMDOPGetEventStatus,           "GetEventStatus","        "},
        {PMDOPSetBreakpointUpdateMask,  "SetBreakpointUpdateMask",""},
        {PMDOPGetBreakpointUpdateMask,  "GetBreakpointUpdateMask",""},
        {PMDOPResetEventStatus,         "ResetEventStatus","      "},
        {0x35,                          "Invalid opcode!","       "},
        {PMDOPGetCaptureValue,          "GetCaptureValue","       "},
        {PMDOPGetActualPosition,        "GetActualPosition","     "},
        {PMDOPSetSampleTime,            "SetSampleTime","         "},
        {PMDOPReset,                    "Reset","                 "},
        {PMDOPGetCurrentMotorCommand,   "GetCurrentMotorCommand",""},
        {PMDOPSetMagellanSampleTime,    "SetMagSampleTime","      "},
        {PMDOPGetMagellanSampleTime,    "GetMagSampleTime","      "},
        {0x3D,                          "Invalid opcode!","       "},
        {PMDOPGetTime,                  "GetTime","               "},
        {0x3F,                          "Invalid opcode!","       "},
        
        {PMDOPGetBusVoltage,            "GetBusVoltage","         "},
        {PMDOPSetCurrentFoldback,       "SetCurrentFoldback","    "},
        {PMDOPGetCurrentFoldback,       "GetCurrentFoldback","    "},
        {PMDOPSetCurrentControlMode,    "SetCurrentControlMode"," "},
        {PMDOPGetCurrentControlMode,    "GetCurrentControlMode"," "},
        {PMDOPSetAxisOutMask,           "SetAxisOutMask","        "},
        {PMDOPGetAxisOutMask,           "GetAxisOutMask","        "},
        {PMDOPClearPositionError,       "ClearPositionError","    "},
        {PMDOPSetEventAction,           "SetEventAction","        "},
        {PMDOPGetEventAction,           "GetEventAction","        "},
        {PMDOPGetPosition,              "GetPosition","           "},
        {PMDOPGetVelocity,              "GetVelocity","           "},
        {PMDOPGetAcceleration,          "GetAcceleration","       "},
        {PMDOPSetActualPosition,        "SetActualPosition","     "},
        {0x4E,                          "Invalid opcode!","       "},
        {0x4F,                          "Invalid opcode!","       "},
        
        {PMDOPGetKp,                    "GetKp","                 "},
        {PMDOPGetKi,                    "GetKi","                 "},
        {PMDOPGetKd,                    "GetKd","                 "},
        {PMDOPGetTemperature,           "GetTemperature","        "},
        {PMDOPGetKvff,                  "GetKvff","               "},
        {PMDOPGetPositionLoopValue,     "GetPositionLoopValue","  "},
        {PMDOPGetInterruptMask,         "GetInterruptMask","      "},
        {PMDOPGetActiveOperatingMode,   "GetActiveOperatingMode",""},
        {PMDOPGetJerk,                  "GetJerk","               "},
        {PMDOPGetGearRatio,             "GetGearRatio","          "},
        {PMDOPGetFOCValue,              "GetFOCValue","           "},
        {PMDOPMultiUpdate,              "MultiUpdate","           "},
        {0x5C,                          "Invalid opcode!","       "},
        {0x5D,                          "Invalid opcode!","       "},
        {PMDOPSetHoldingCurrent,        "SetHoldingCurrent","     "},
        {PMDOPGetHoldingCurrent,        "GetHoldingCurrent","     "},
        
        {PMDOPGetBusVoltageLimits,      "GetBusVoltageLimits","   "},
        {PMDOPGetSampleTime,            "GetSampleTime","         "},
        {PMDOPSetBusVoltageLimits,      "SetBusVoltageLimits","   "},
        {PMDOPGetBusVoltageLimits,      "GetBusVoltageLimits","   "},
        {0x64,                          "Invalid opcode!","       "},
        {PMDOPSetOperatingMode,         "SetOperatingMode","      "},
        {PMDOPGetOperatingMode,         "GetOperatingMode","      "},
        {PMDOPSetPositionLoop,          "SetPositionLoop","       "},
        {PMDOPGetPositionLoop,          "GetPositionLoop","       "},
        {PMDOPGetMotorCommand,          "GetMotorCommand","       "},
        {PMDOPSetStartVelocity,         "SetStartVelocity","      "},
        {PMDOPGetStartVelocity,         "GetStartVelocity","      "},
        {PMDOPClearDriveFaultStatus,    "ClearDriveFaultStatus"," "},
        {PMDOPGetDriveFaultStatus,      "GetDriveFaultStatus","   "},
        {PMDOPGetOutputMode,            "GetOutputMode","         "},
        {0x6F,                          "Invalid opcode!","       "},
        
        {0x70,                          "Invalid opcode!","       "},
        {PMDOPGetCurrentLoopValue,      "GetCurrentLoopValue","   "},
        {PMDOPSetPhaseInitializeTime,   "SetPhaseInitializeTime",""},
        {PMDOPSetCurrentLoop,           "SetCurrentLoop","        "},
        {PMDOPGetCurrentLoop,           "GetCurrentLoop","        "},
        {PMDOPSetPhaseCounts,           "SetPhaseCounts","        "},
        {PMDOPSetPhaseOffset,           "SetPhaseOffset","        "},
        {PMDOPSetMotorCommand,          "SetMotorCommand","       "},
        {0x78,                          "Invalid opcode!","       "},
        {0x79,                          "Invalid opcode!","       "},
        {PMDOPInitializePhase,          "InitializePhase","       "},
        {PMDOPGetPhaseOffset,           "GetPhaseOffset","        "},
        {PMDOPGetPhaseInitializeTime,   "GetPhaseInitializeTime",""},
        {PMDOPGetPhaseCounts,           "GetPhaseCounts","        "},
        {0x7E,                          "Invalid opcode!","       "},
        {0x7F,                          "Invalid opcode!","       "},
        
        {PMDOPSetLimitSwitchMode,       "SetLimitSwitchMode","    "},
        {PMDOPGetLimitSwitchMode,       "GetLimitSwitchMode","    "},
        {PMDOPWriteIO,                  "WriteIO","               "},
        {PMDOPReadIO,                   "ReadIO","                "},
        {PMDOPSetPhaseAngle,            "SetPhaseAngle","         "},
        {PMDOPSetNumberPhases,          "SetNumberPhases","       "},
        {PMDOPGetNumberPhases,          "GetNumberPhases","       "},
        {PMDOPSetAxisMode,              "SetAxisMode","           "},
        {PMDOPGetAxisMode,              "GetAxisMode","           "},
        {PMDOPSetDiagnosticPortMode,    "SetDiagnosticPortMode"," "},
        {PMDOPGetDiagnosticPortMode,    "GetDiagnosticPortMode"," "},
        {PMDOPSetSerialPortMode,        "SetSerialPortMode","     "},
        {PMDOPGetSerialPortMode,        "GetSerialPortMode","     "},
        {PMDOPSetEncoderModulus,        "SetEncoderModulus","     "},
        {PMDOPGetEncoderModulus,        "GetEncoderModulus","     "},
        {PMDOPGetVersion,               "GetVersion","            "},
        
        {PMDOPSetAcceleration,          "SetAcceleration","       "},
        {PMDOPSetDeceleration,          "SetDeceleration","       "},
        {PMDOPGetDeceleration,          "GetDeceleration","       "},
        {PMDOPSetKaff,                  "SetKaff","               "},
        {PMDOPGetKaff,                  "GetKaff","               "},
        {PMDOPSetIntegrationLimit,      "SetIntegrationLimit","   "},
        {PMDOPGetIntegrationLimit,      "GetIntegrationLimit","   "},
        {PMDOPSetPositionErrorLimit,    "SetPositionErrorLimit"," "},
        {PMDOPGetPositionErrorLimit,    "GetPositionErrorLimit"," "},
        {PMDOPGetPositionError,         "GetPositionError","      "},
        {PMDOPGetIntegral,              "GetIntegral","           "},
        {PMDOPGetDerivative,            "GetDerivative","         "},
        {PMDOPSetDerivativeTime,        "SetDerivativeTime","     "},
        {PMDOPGetDerivativeTime,        "GetDerivativeTime","     "},
        {PMDOPSetKout,                  "SetKout","               "},
        {PMDOPGetKout,                  "GetKout","               "},
        
        {PMDOPSetProfileMode,           "SetProfileMode","        "},
        {PMDOPGetProfileMode,           "GetProfileMode","        "},
        {PMDOPSetSignalSense,           "SetSignalSense","        "},
        {PMDOPGetSignalSense,           "GetSignalSense","        "},
        {PMDOPGetSignalStatus,          "GetSignalStatus","       "},
        {PMDOPGetHostIOError,           "GetHostIOError","        "},
        {PMDOPGetActivityStatus,        "GetActivityStatus","     "},
        {PMDOPGetCommandedAcceleration, "GetCommandedAcceleration",""},
        {PMDOPSetTrackingWindow,        "SetTrackingWindow","     "},
        {PMDOPGetTrackingWindow,        "GetTrackingWindow","     "},
        {PMDOPSetSettleTime,            "SetSettleTime","         "},
        {PMDOPGetSettleTime,            "GetSettleTime","         "},
        {PMDOPClearInterrupt,           "ClearInterrupt","        "},
        {PMDOPGetActualVelocity,        "GetActualVelocity","     "},
        {PMDOPSetGearMaster,            "SetGearMaster","         "},
        {PMDOPGetGearMaster,            "GetGearMaster","         "},
        
        {PMDOPSetTraceMode,             "SetTraceMode","          "},
        {PMDOPGetTraceMode,             "GetTraceMode","          "},
        {PMDOPSetTraceStart,            "SetTraceStart","         "},
        {PMDOPGetTraceStart,            "GetTraceStart","         "},
        {PMDOPSetTraceStop,             "SetTraceStop","          "},
        {PMDOPGetTraceStop,             "GetTraceStop","          "},
        {PMDOPSetTraceVariable,         "SetTraceVariable","      "},
        {PMDOPGetTraceVariable,         "GetTraceVariable","      "},
        {PMDOPSetTracePeriod,           "SetTracePeriod","        "},
        {PMDOPGetTracePeriod,           "GetTracePeriod","        "},
        {PMDOPGetTraceStatus,           "GetTraceStatus","        "},
        {PMDOPGetTraceCount,            "GetTraceCount","         "},
        {PMDOPSetSettleWindow,          "SetSettleWindow","       "},
        {PMDOPGetSettleWindow,          "GetSettleWindow","       "},
        {PMDOPSetActualPositionUnits,   "SetActualPositionUnits",""},
        {PMDOPGetActualPositionUnits,   "GetActualPositionUnits",""},
        
        {PMDOPSetBufferStart,           "SetBufferStart","        "},
        {PMDOPGetBufferStart,           "GetBufferStart","        "},
        {PMDOPSetBufferLength,          "SetBufferLength","       "},
        {PMDOPGetBufferLength,          "GetBufferLength","       "},
        {PMDOPSetBufferWriteIndex,      "SetBufferWriteIndex","   "},
        {PMDOPGetBufferWriteIndex,      "GetBufferWriteIndex","   "},
        {PMDOPSetBufferReadIndex,       "SetBufferReadIndex","    "},
        {PMDOPGetBufferReadIndex,       "GetBufferReadIndex","    "},
        {PMDOPWriteBuffer,              "WriteBuffer","           "},
        {PMDOPReadBuffer,               "ReadBuffer","            "},
        {PMDOPSetBufferFunction,        "SetBufferFunction","     "},
        {PMDOPGetBufferFunction,        "GetBufferFunction","     "},
        {0xCC,                          "Invalid opcode!","       "},
        {0xCD,                          "Invalid opcode!","       "},
        {PMDOPGetStepRange,             "SetStepRange","          "},
        {PMDOPSetStepRange,             "GetStepRange","          "},
        
        {PMDOPSetStopMode,              "SetStopMode","           "},
        {PMDOPGetStopMode,              "GetStopMode","           "},
        {PMDOPSetAutoStopMode,          "SetAutoStopMode","       "},
        {PMDOPGetAutoStopMode,          "GetAutoStopMode","       "},
        {PMDOPSetBreakpoint,            "SetBreakpoint","         "},
        {PMDOPGetBreakpoint,            "GetBreakpoint","         "},
        {PMDOPSetBreakpointValue,       "SetBreakpointValue","    "},
        {PMDOPGetBreakpointValue,       "GetBreakpointValue","    "},
        {PMDOPSetCaptureSource,         "SetCaptureSource","      "},
        {PMDOPGetCaptureSource,         "GetCaptureSource","      "},
        {PMDOPSetEncoderSource,         "SetEncoderSource","      "},
        {PMDOPGetEncoderSource,         "GetEncoderSource","      "},
        {PMDOPSetMotorMode,             "SetMotorMode","          "},
        {PMDOPGetMotorMode,             "GetMotorMode","          "},
        {PMDOPSetEncoderToStepRatio,    "SetEncoderToStepRatio"," "},
        {PMDOPGetEncoderToStepRatio,    "GetEncoderToStepRatio"," "},
        
        {PMDOPSetOutputMode,            "SetOutputMode","         "},
        {PMDOPGetInterruptAxis,         "GetInterruptAxis","      "},
        {PMDOPSetCommutationMode,       "SetCommutationMode","    "},
        {PMDOPGetCommutationMode,       "GetCommutationMode","    "},
        {PMDOPSetPhaseInitializeMode,   "SetPhaseInitializeMode",""},
        {PMDOPGetPhaseInitializeMode,   "GetPhaseInitializeMode",""},
        {PMDOPSetPhasePrescale,         "SetPhasePrescale","      "},
        {PMDOPGetPhasePrescale,         "GetPhasePrescale","      "},
        {PMDOPSetPhaseCorrectionMode,   "SetPhaseCorrectionMode",""},
        {PMDOPGetPhaseCorrectionMode,   "GetPhaseCorrectionMode",""},
        {PMDOPGetPhaseCommand,          "GetPhaseCommand","       "},
        {PMDOPSetMotionCompleteMode,    "SetMotionCompleteMode"," "},
        {PMDOPGetMotionCompleteMode,    "GetMotionCompleteMode"," "},
        {PMDOPSetAxisOutSource,         "SetAxisOutSource","      "},
        {PMDOPGetAxisOutSource,         "GetAxisOutSource","      "},
        {PMDOPReadAnalog,               "ReadAnalog","            "},
        
        {0xF0,                          "Invalid opcode!","       "},
        {0xF1,                          "Invalid opcode!","       "},
        {PMDOPSetSynchronizationMode,   "SetSyncMode(Mag)","      "},
        {PMDOPGetSynchronizationMode,   "GetSyncMode(Mag)","      "},
        {0xF4,                          "Invalid opcode!","       "},
        {PMDOPAdjustActualPosition,     "AdjustActualPosition","  "},
        {PMDOPSetFOC,                   "SetFOC","                "},
        {PMDOPGetFOC,                   "GetFOC","                "},
        {PMDOPGetChecksum,              "GetChecksum","           "},
        {PMDOPSetUpdateMask,            "SetUpdateMask","         "},
        {PMDOPGetUpdateMask,            "GetUpdateMask","         "},
        {PMDOPSetFaultOutMask,          "SetFaultOutMask","       "},
        {PMDOPGetFaultOutMask,          "GetFaultOutMask","       "},
        {0xFD,                          "Invalid opcode!","       "},
        {0xFE,                          "Invalid opcode!","       "},
        {0xFF,                          "Invalid opcode!","       "}
};

#if defined(__cplusplus)
}
#endif

#endif

